# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2

jobs:
  testing:
    docker:
      - image: p5ych0/php-fpm

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          name: PHP Composer Cache
          keys:
          - v1-dependencies-{{ checksum "composer.lock" }}
          - v1-dependencies-

      - run:
          name: Installing Composer dependencies
          command: composer install

      - save_cache:
          name: Save Composer Cache
          paths:
            - backend/vendor
          key: v1-dependencies-{{ checksum "composer.lock" }}

      # run tests!
      - run:
          name: Testing
          working_directory: ./backend
          command: vendor/bin/phpunit

workflows:
  version: 2
  test-only:
    jobs:
      - testing
